version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    assignees:
      - "@rovergulf/ng-engineers"
    open-pull-requests-limit: 20
