name: Build and Publish to GCR

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on: workflow_dispatch

jobs:
  setup-build-publish:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    environment: gcr
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCR_ACCESS_CREDENTIALS }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: gcloud --quiet auth configure-docker

      # Build the Docker image
      - name: Build and Publish
        run: ./scripts/build_and_publish_gcr.sh
        env:
          REGISTRY_IMAGE: ${{ secrets.OCI_REGISTRY_IMAGE }}
