name: Node.js CI

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-kit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 15.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint ngx-slice-kit
      - run: npm run test:kit
      - run: npm run codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
